backend/p_front/urls.py
from django.urls import path, include

from .views import *

app_name = 'front'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about', AboutView.as_view(), name='about'),
    path('works', WorksListView.as_view(), name='works_lists'),
    path('contacts', ContactView.as_view(), name='contact_us'),
    path('works-details', WorksDetailView.as_view(), name='works_details'),
]

backend/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('p_front.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/p_front/models.py
from django.db import models
from django.utils import timezone

# Creating works listing

class Works(models.Model):
    title = models.CharField(max_length=255, null=True, blank=False)
    role = models.CharField(max_length=255, null=True, blank=False)
    year = models.DateTimeField()
    client = models.CharField(max_length=255, null=True, blank=False)
    description = models.TextField()
    image = models.ImageField(upload_to='media/works/', null=True, blank=True)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.title

backend/p_front/views.py
# from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.http import Http404, HttpResponseRedirect
from .models import Works

# Creating your views here.
class HomeView(TemplateView):
    template_name = 'index.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class ContactView(TemplateView):
    template_name = 'contact.html'


class WorksListView(ListView):
    model = Works
    template_name = 'works.html'
    context_object_name = 'works_list'
    
    def get_quesryset(self):
        return self.model.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['worklists'] = self.model.objects.all()
        
        return context


class WorksDetailView(DetailView):
    model = Works
    template_name = 'work-details.html'
    context_object_name = 'works_details'
    slug_field = 'role'
    slug_url_kwarg = 'role'
    
    def get_queryset(self):
        return self.model.objects.filter(is_published=True)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description" content="Digital Agency and Portfolio Template">
    <meta name="keywords" content="Digital Agency, Agency, Business, Portfolio, Personal, Creative, Html Template, Portfolio Template">
    <meta name="author" content="ixTheme">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Title -->
    {% if title %}
    <title>PM - {{ title }}</title>
    {% else %}
    <title>PM</title>
    {% endif %}
    <!-- Favicon -->
    <link href="static/img/favicon.png" type="image/png" rel="icon">

    <!-- All CSS -->
    <link href="static/css/plugins.css" rel="stylesheet" type="text/css">
    <link href="static/css/main.css" rel="stylesheet" type="text/css">
    <link href="static/css/responsive.css" rel="stylesheet" type="text/css">
</head>

<body>
    <!-- page cursor -->
    <div id="cursor" class="cursor"></div>

    <!--  start page loader  -->
    <div id="preloader">
        <div class="loader__content"></div>
        <div class="loader__content"></div>
        <div class="scroll-static"></div>
    </div>
    <!--  end page loader  -->

    <!-- start sidebar -->
    <div class="sidebar__left">

        <!-- navigation toggle -->
        <div class="navigation__toggle hbrable">
            <span></span><span></span><span></span>
        </div>

        <!-- color chooser toggle -->
        <div class="color__chooser_toggle hbrable"></div>

        <!-- breadcrumb text -->
        <div class="breadcrumb__text">
            {% if request.path == 'home' %}
            <span>Home</span> {% elif request.path == 'about' %}
            <span>About</span> {% endif %}
        </div>
    </div>
    <!-- end sidebar -->
    <!-- start navigation -->
    <nav class="navigation">
        <div class="container-fluid h-100">
            <div class="row no-gutters justify-content-center align-items-center h-100">
                <div class="col-md-4">
                    <div class="navigation_inner">
                        <div class="nav__label">
                            <a href="/" class="active nav__label_inner slide-horizontal hbrable" data-splitting>Home</a>
                        </div>
                        <div class="nav__label">
                            <a href="{% url 'front:about' %}" class="nav__label_inner slide-horizontal hbrable" data-splitting>About</a>
                        </div>
                        <div class="nav__label">
                            <a href="{% url 'front:works_lists' %}" class="nav__label_inner slide-horizontal hbrable" data-splitting>Works</a>
                        </div>
                        <div class="nav__label">
                            <a href="journal.html" class="nav__label_inner slide-horizontal hbrable" data-splitting>Journal</a>
                        </div>
                        <div class="nav__label">
                            <a href="{% url 'front:contact_us' %}" class="nav__label_inner slide-horizontal hbrable" data-splitting>Contact</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="contact__info mb-0">
                        <!-- hire me -->
                        <div class="text__heading_sm">Hire</div>

                        <!-- contact info -->
                        <div class="direct__contact_info">
                            <p>pmburu@pm.co.ke</p>
                            <p>+254 723 176 484</p>
                        </div>
                        <!-- follow -->
                        <div class="text__heading_sm">Follow</div>

                        <!-- social links -->
                        <div class="social__links">
                            <a class="hbrable" href="#0">
                                <span class="ti-twitter"></span>
                            </a>
                            <a class="hbrable" href="#0">
                                <span class="ti-linkedin"></span>
                            </a>
                            <a class="hbrable" href="#0">
                                <span class="ti-instagram"></span>
                            </a>
                            <a class="hbrable" href="#0">
                                <span class="ti-facebook"></span>
                            </a>
                            <a class="hbrable" href="#0">
                                <span class="ti-dribbble"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <!-- end navigation -->
    {% block content %} {% block footer %}
    <!-- start footer wrapper -->
    <footer class="footer__wrapper wrapper__alt">
        <div class="container">
            <div class="row justify-content-center align-items-center">
                <div class="col-lg-4 col-md-6 order-md-first order-sm-last order-last">
                    <p class="copyright__text">&copy; 2019 <a class="hbrable" href="pm.co.ke">Peter Mburu</a> All Rights Reserved.</p>
                </div>
                <div class="col-lg-4 col-md-6 order-md-last order-sm-first order-first">
                    <div class="social__links">
                        <a class="hbrable" href="https://twitter.com/MburuNgige" target="\_blank">
                            <span class="ti-twitter"></span>
                        </a>
                        <a class="hbrable" href="#0">
                            <span class="ti-linkedin"></span>
                        </a>
                        <a class="hbrable" href="#0">
                            <span class="ti-instagram"></span>
                        </a>
                        <a class="hbrable" href="#0">
                            <span class="ti-facebook"></span>
                        </a>
                        <a class="hbrable" href="#0">
                            <span class="ti-dribbble"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- end footer wrapper -->
    {% endblock footer %}{% endblock content %}
    <!-- All JS -->
    <script src="static/js/jquery-3.3.1.min.js"></script>
    <script src="static/js/plugins.js"></script>
    <script src="static/js/main.js"></script>

</body>

</html>

templates/contact.html
{% extends "base.html" %} {% block content %}
<!-- start main-content of contact wrapper -->
<div id="luxy" class="main__content luxy__wrapper">

    <!-- start hero/breadcrumb wrapper -->
    <div class="wrapper wrapper__alt">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-12">
                    <h2 class="page__hero_title slide__in_right" data-splitting>
                        <i>Contact Me.</i>
                        <span class="sub__text">Get in Touch</span>
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <!-- end hero/breadcrumb wrapper -->

    <!-- start contact form wrapper -->
    <div class="wrapper contact__form_wrapper">

        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-12">

                    <!-- contact__form -->
                    <form method="POST" class="contact__form">
                        <div class="row justify-content-between">
                            <div class="col-md-12">
                                <div class="row contact__info">
                                    <div class="col-md-6">
                                        <!-- hire me -->
                                        <p class="text__heading_sm">Hire</p>

                                        <!-- contact info -->
                                        <div class="direct__contact_info">
                                            <p>pmburu@pm.co.ke</p>
                                            <p>+254 723 176 484</p>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <!-- follow -->
                                        <p class="text__heading_sm">Follow</p>

                                        <!-- social links -->
                                        <div class="social__links">
                                            <a class="hbrable" href="#0">
                                                <span class="ti-twitter"></span>
                                            </a>
                                            <a class="hbrable" href="#0">
                                                <span class="ti-linkedin"></span>
                                            </a>
                                            <a class="hbrable" href="#0">
                                                <span class="ti-instagram"></span>
                                            </a>
                                            <a class="hbrable" href="#0">
                                                <span class="ti-facebook"></span>
                                            </a>
                                            <a class="hbrable" href="#0">
                                                <span class="ti-dribbble"></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-12">
                                        <!-- contact__form_text -->
                                        <h3 class="contact__form_heading">Business Talk</h3>
                                    </div>
                                    <div class="col-md-12 contact__form_services">
                                        <!-- input checkbox for service -->
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="frontED">
                                            <label class="custom-control-label" for="frontED">Front-end Development</label>
                                        </div>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="webD">
                                            <label class="custom-control-label" for="webD">Website Design</label>
                                        </div>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="UId">
                                            <label class="custom-control-label" for="UId">UI Design</label>
                                        </div>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="UXr">
                                            <label class="custom-control-label" for="UXr">UX Research</label>
                                        </div>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="nobAD">
                                            <label class="custom-control-label" for="nobAD">Mobile App Design</label>
                                        </div>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="bran">
                                            <label class="custom-control-label" for="bran">Branding</label>
                                        </div>
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="anim">
                                            <label class="custom-control-label" for="anim">Animation</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <!-- input field for NAME -->
                                        <input class="input_field required" type="text" name="name" placeholder="Full Name">
                                    </div>
                                    <div class="col-md-6">
                                        <!-- input field for EMAIL -->
                                        <input class="input_field required" type="email" name="email" placeholder="Email Address">
                                    </div>
                                    <div class="col-md-12">
                                        <!-- input field for MESSAGE -->
                                        <textarea class="input_field required" name="message" placeholder="Just write “hello” or describe it"></textarea>
                                    </div>
                                    <div class="col-md-12 text-center">
                                        <!-- button for MESSAGE-SEND -->
                                        <button class="button-default slide-vertical hbrable" type="submit" data-splitting>send message</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- end contact form wrapper -->

</div>
<!-- end main-content of contact wrapper -->
{% endblock content %}

templates/css/overlays/02.png.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /html/kuber/css/overlays/02.png was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

templates/css/owl.video.play.png.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /html/kuber/css/owl.video.play.png was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

templates/img/img1.jpg.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /html/kuber/img/img1.jpg was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

templates/index-2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Digital Agency and Portfolio Template">
    <meta name="keywords" content="Digital Agency, Agency, Business, Portfolio, Personal, Creative, Html Template, Portfolio Template">
    <meta name="author" content="ixTheme">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Title -->
    <title>Kuber - Portfolio Template</title>
    <!-- Favicon -->
    <link href="img/favicon.png" type="image/png" rel="icon">

    <!-- All CSS -->
    <link href="css/plugins.css" rel="stylesheet" type="text/css">
    <link href="css/main.css" rel="stylesheet" type="text/css">
    <link href="css/responsive.css" rel="stylesheet" type="text/css">
</head>

<body>

    <!-- page cursor -->
    <div id="cursor" class="cursor"></div>

    <!--  start page loader  -->
    <div id="preloader">
        <div class="loader__content"></div>
        <div class="scroll-static"></div>
    </div>
    <!--  end page loader  -->

    <!-- start sidebar -->
    <div class="sidebar__left">

        <!-- navigation toggle -->
        <div class="navigation__toggle hbrable">
            <span></span><span></span><span></span>
        </div>

        <!-- color chooser toggle -->
        <div class="color__chooser_toggle hbrable"></div>

        <!-- breadcrumb text -->
        <div class="breadcrumb__text">
            <span>Home</span>
        </div>
    </div>
    <!-- end sidebar -->

    <!-- start navigation -->
    <nav class="navigation">
        <div class="container-fluid h-100">
            <div class="row no-gutters justify-content-center align-items-center h-100">
                <div class="col-md-4">
                    <div class="navigation_inner">
                        <div class="nav__label submenu__wrap">
                            <span class="nav__label_inner active slide-horizontal hbrable" data-splitting>Home</span>
                            <ul class="sub__menu">
                                <li><a class="hbrable" href="index.html">Glitch Image</a></li>
                                <li><a class="active hbrable" href="index-2.html">Background Image</a></li>
                                <li><a class="hbrable" href="index-3.html">Kenburns SlideShow</a></li>
                            </ul>
                        </div>
                        <div class="nav__label">
                            <a href="about.html" class="nav__label_inner slide-horizontal hbrable" data-splitting>About</a>
                        </div>
                        <div class="nav__label submenu__wrap">
                            <span class="nav__label_inner slide-horizontal hbrable" data-splitting>Works</span>
                            <ul class="sub__menu">
                                <li><a class="hbrable" href="works.html">Works Modern</a></li>
                                <li><a class="hbrable" href="works-grid.html">Works Grid View</a></li>
                                <li><a class="hbrable" href="works-grid-overlay.html">Works Grid Overlay</a></li>
                            </ul>
                        </div>
                        <div class="nav__label">
                            <a href="journal.html" class="nav__label_inner slide-horizontal hbrable" data-splitting>Journal</a>
                        </div>
                        <div class="nav__label">
                            <a href="contact.html" class="nav__label_inner slide-horizontal hbrable" data-splitting>Contact</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="contact__info mb-0">
                        <!-- hire me -->
                        <div class="text__heading_sm">Hire</div>

                        <!-- contact info -->
                        <div class="direct__contact_info">
                            <p>contact@yoursite.com</p>
                            <p>+1 234 567 8902</p>
                        </div>
                        <!-- follow -->
                        <div class="text__heading_sm">Follow</div>

                        <!-- social links -->
                        <div class="social__links">
                            <a class="hbrable" href="#0">
                                <span class="ti-twitter"></span>
                            </a>
                            <a class="hbrable" href="#0">
                                <span class="ti-linkedin"></span>
                            </a>
                            <a class="hbrable" href="#0">
                                <span class="ti-instagram"></span>
                            </a>
                            <a class="hbrable" href="#0">
                                <span class="ti-facebook"></span>
                            </a>
                            <a class="hbrable" href="#0">
                                <span class="ti-dribbble"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- end navigation -->

    
    <!-- start main content -->
    <div class="main__content background__img h-100" data-bgi="img/author01.jpg">
        <div class="container h-100">
            <div class="row h-100 justify-content-center align-items-center">
                <div class="col-md-10">
                    <!-- start hero__wrapper -->
                    <div class="hero__wrapper">
                        <div class="hero__content">
                            <h5 class="title__person slide__in_right" data-splitting>Jack Barker</h5>
                            <p class="title__person_info slide__in_right" data-splitting>A Digital Product &amp; UI Designer.<br>Lives in San Francisco.</p>
                        </div>
                        <div class="hero__socials">
                            <a href="#0" class="social__label slide__in_right slide-horizontal hbrable" data-splitting>Twitter</a>
                            <a href="#0" class="social__label slide__in_right slide-horizontal hbrable" data-splitting>Linkedin</a>
                            <a href="#0" class="social__label slide__in_right slide-horizontal hbrable" data-splitting>Dribbble</a>
                        </div>
                    </div>
                    <!-- end hero__wrapper -->
                </div>
            </div>
        </div>
    </div>
    <!-- end main content -->


    <!-- All JS -->
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/plugins.js"></script>
    <script src="js/main.js"></script>

</body>

</html>

templates/index.html
{% extends "base.html" %} {% block content %}

<!-- start main content -->
<div class="main__content glitch__image h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-lg-4 overflow-hidden">
                <!-- hero person image -->
                <div class="hero__person_image">
                    <div class="glitch">
                        <div class="glitch__img"></div>
                        <div class="glitch__img"></div>
                        <div class="glitch__img"></div>
                        <div class="glitch__img"></div>
                        <div class="glitch__img"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <!-- start hero__wrapper -->
                <div class="hero__wrapper">
                    <div class="hero__content">
                        <h5 class="title__person slide__in_right" data-splitting>Peter Mburu</h5>
                        <p class="title__person_info slide__in_right" data-splitting>A Backend (Python) Sofware Engineer.<br>Living in Nairobi, Kenya.</p>
                    </div>
                    <div class="hero__socials">
                        <a href="https://twitter.com/MburuNgige" target="\_blank" rel="noopener noreferrer" class="social__label slide__in_right slide-horizontal hbrable" data-splitting>Twitter</a>
                        <a href="#0" class="social__label slide__in_right slide-horizontal hbrable" data-splitting>Linkedin</a>
                        <a href="#0" class="social__label slide__in_right slide-horizontal hbrable" data-splitting>Dribbble</a>
                    </div>
                </div>
                <!-- end hero__wrapper -->
            </div>
        </div>
    </div>
</div>
<!-- end main content -->
{% endblock content %}

templates/works.html
{% extends "base.html" %} {% block content %}

<!-- start main-content of about wrapper -->
<div id="luxy" class="main__content luxy__wrapper">
    <!-- start hero/breadcrumb wrapper -->
    <div class="wrapper wrapper__alt">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-12">
                    <h2 class="page__hero_title slide__in_right" data-splitting>
                        <i>Portfolio.</i>
                        <span class="sub__text">Our Best Works</span>
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <!-- end hero/breadcrumb wrapper -->

    <!-- start works wrapper -->
    <div class="wrapper works__wrapper">
        <div class="container">
            <div class="row justify-content-center">
                {% for worklist in worklists %}
                <div class="col-lg-8 col-md-12">
                    <!-- work-item -->
                    <div class="works__item">
                        <h2 class="work__title">
                            <span class="project__count">06</span>
                            <a class="ajax-popup-link hbrable" href="{% url 'front:works_details' %}">{{ worklist.title }}</a>
                        </h2>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- end works wrapper -->

    <!-- start promo wrapper -->
    <div class="wrapper promo__wrapper wrapper__alt">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-12">
                    <h2>Start your project or scale your team with us.</h2>
                    <a class="button-default slide-vertical hbrable" href="contact.html" data-splitting>Contact Us</a>
                </div>
            </div>
        </div>
    </div>
    <!-- end promo wrapper -->

    {% endblock content %}